# Heavily inspired by https://github.com/NixOS/nixpkgs/blob/a698ac1214cd924d4394ca9cd2691618765aa03c/.github/workflows/backport.yml

name: "On Backport Label"

permissions:
  pull-requests: write
  contents: write

on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    if: github.event.pull_request.labels && contains(join(github.event.pull_request.labels.*.name, ', '), 'backport ')
    name: Backport PR 🔙
    runs-on: ubuntu-latest
    outputs:
      created_pull_numbers: ${{ steps.backport.outputs.created_pull_numbers }}
    steps:
      - name: Check actor permissions
        id: check-permissions
        uses: prince-chrismc/check-actor-permissions-action@v3.0.2
        with:
          permission: write

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Create backport PR
        id: backport
        uses: korthout/backport-action@v3.2.1
        with:
          merge_commits: "skip"
          add_author_as_assignee: true
          copy_requested_reviewers: true

  trigger-ci:
    name: Trigger CI on created branches 🚀
    needs: backport
    strategy:
      matrix:
        pr: fromJSON("[${{ needs.backport.outputs.created_pull_numbers }}]")
    uses: ./.github/workflows/run_trigger_backport_ci.yml
    with:
      pr: ${{ matrix.pr }}
